username: edem.agbakpe@outlook.com
password: cruzer54l
phone_number: +233553892665

profile_path: 'https://www.linkedin.com/in/edem-agbakpe/' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- Fullstack


locations:
- Remote

salary: 7,000
rate: 25
# --------- Optional Parameters -------
uploads:
  Resume: /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/cv.pdf
  Cover Letter: /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/cl.pdf
  #Photo: # PATH TO photo


output_filename:
- /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/out.csv

# blacklist:
# - # Company names you want to ignore
